// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCopa26.Data;

#nullable disable

namespace PortalCopa26.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("Letra")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Letra")
                        .IsUnique();

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gols")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParticipacoesCopas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GolsMandante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GolsVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MandanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rotulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VagaMandante")
                        .HasColumnType("TEXT");

                    b.Property<string>("VagaVisitante")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VisitanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("MandanteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("VisitanteId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.RankingFifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoSelecao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSelecao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Pontos")
                        .HasColumnType("REAL");

                    b.Property<int>("Posicao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelecaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Posicao")
                        .IsUnique();

                    b.HasIndex("SelecaoId");

                    b.ToTable("RankingsFifa");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Selecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CabecaDeChave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tecnico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("GrupoId");

                    b.ToTable("Selecoes");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VisitanteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VisitanteId");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.SimulacaoJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsMandante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimulacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("SimulacaoId", "JogoId")
                        .IsUnique();

                    b.ToTable("SimulacoesJogos", t =>
                        {
                            t.HasCheckConstraint("CK_SimulacaoJogo_GolsMandante_Faixa", "GolsMandante >= 0 AND GolsMandante <= 30");

                            t.HasCheckConstraint("CK_SimulacaoJogo_GolsVisitante_Faixa", "GolsVisitante >= 0 AND GolsVisitante <= 30");
                        });
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Jogador", b =>
                {
                    b.HasOne("PortalCopa26.Domain.Entities.Selecao", "Selecao")
                        .WithMany("Jogadores")
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Selecao");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Jogo", b =>
                {
                    b.HasOne("PortalCopa26.Domain.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalCopa26.Domain.Entities.Selecao", "Mandante")
                        .WithMany()
                        .HasForeignKey("MandanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalCopa26.Domain.Entities.Selecao", "Visitante")
                        .WithMany()
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grupo");

                    b.Navigation("Mandante");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.RankingFifa", b =>
                {
                    b.HasOne("PortalCopa26.Domain.Entities.Selecao", "Selecao")
                        .WithMany()
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Selecao");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Selecao", b =>
                {
                    b.HasOne("PortalCopa26.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Selecoes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.SimulacaoJogo", b =>
                {
                    b.HasOne("PortalCopa26.Domain.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalCopa26.Domain.Entities.Simulacao", "Simulacao")
                        .WithMany("Jogos")
                        .HasForeignKey("SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Selecoes");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Selecao", b =>
                {
                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("PortalCopa26.Domain.Entities.Simulacao", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
